# Generated by generate.sh - do not edit directly.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit-{{DEPLOY_NAME}}-sa
  namespace: {{NAMESPACE}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbit-{{DEPLOY_NAME}}-cluster-role
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentbit-{{DEPLOY_NAME}}-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentbit-{{DEPLOY_NAME}}-cluster-role
subjects:
- kind: ServiceAccount
  name: fluentbit-{{DEPLOY_NAME}}-sa
  namespace: {{NAMESPACE}}
