FROM secureimages/filebeat-oss:7.11.1-alpine-3.13.2
COPY ./conf/filebeat-k8s.yml /usr/share/filebeat/filebeat.yml
COPY ./filebeat-entrypoint.sh /filebeat-entrypoint.sh
USER root
RUN chmod +x /filebeat-entrypoint.sh
RUN chmod go-w /usr/share/filebeat/filebeat.yml
USER filebeat