filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/lib/docker/containers/${data.container.id}/*.log  # CRI path
        ignore_older: 24h
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - "/opt/data/log/*/*.log"
    fields_under_root: true
    processors:
      - dissect:
          tokenizer: "/opt/data/log/%{log_type}/*.log"
          field: "log.file.path"
          target_prefix: "kami"
processors:
- add_cloud_metadata: ~
- add_fields:
    target: tenant
    fields:
      name: '${TENANT_NAME:unknown}'
      id: '${TENANT_ID:unknown}'
      roleName: ${ROLE_NAME:unknown}
- add_fields:
    target: ''
    fields:
      tenantLevelIndex: '${TENANT_LEVEL_INDEX:unknown}'
- add_fields:
    target: ''
    fields:
      datastream: '${ALIAS:unknown}'
- drop_fields:
    fields: docker.container.labels
    ignore_missing: true
setup.template.name: "filebeat-%{[agent.version]}"
setup.template.pattern: "filebeat-%{[agent.version]}-*"
setup.template.enabled: ${FILEBEAT_SETUP_TEMPLATE_ENABLED:true}
output.elasticsearch:
  hosts: '${ELASTIC_HOST}'
  indices:
    - index: "%{[datastream]}"
      when.not.equals:
        datastream: "unknown"
    - index: "filebeat-%{[agent.version]}-%{[tenant.name]}-%{[docker.attrs.ROLE_NAME]}-%{+yyyy.MM.dd}"
      when.equals:
        serviceLevelIndex: "yes"
    - index: "tomcat-%{[agent.version]}-%{[tenant.name]}-%{+yyyy.MM.dd}"
      when.equals:
        tenantLevelIndex: "yes"
    - index: "tomcat-%{[agent.version]}-kami-%{+yyyy.MM.dd}"    # New index for kami prefixed fields
      when.has_fields: ["kami.log_type"]
  bulk_max_size: '${BULK_MAX_SIZE:50}'
  worker: '${WORKER_COUNT:1}'
