filebeat.inputs:
  - type: kafka
    hosts: ['${KAFKA_HOST}']
    topics: ["state", "healthcheck"]
    group_id: '${KAFKA_GROUP_ID}'
    auto_offset_reset: "earliest"
processors:
- add_cloud_metadata: ~
#Currently TENANT_NAME is not passed as ENV variable. Using labels to extract TENANT_NAME
- copy_fields:
    fields:
      - from: "kubernetes.labels.tenantname"
        to: "tenant.name"
      - from: "kubernetes.labels.tenantid"
        to: "tenant.id"
    fail_on_error: false
    ignore_missing: true
#strip out duploservice- and actual TENANT_NAME
- replace:
    fields:
      - field: "tenant.name"
        pattern: "duploservices-"
        replacement: ""
    ignore_missing: true
    fail_on_error: false
#Add fields to support tenant level index
- add_fields:
    target: ''
    fields:
      tenantLevelIndex: '${TENANT_LEVEL_INDEX:unknown}'
- add_fields:
    target: ''
    fields:
      datastream: '${ALIAS:unknown}'         
setup.template.name: "filebeat-%{[agent.version]}"
setup.template.pattern: "filebeat-%{[agent.version]}-*"
setup.template.enabled: ${FILEBEAT_SETUP_TEMPLATE_ENABLED:true}
output.elasticsearch:
  hosts: '${ELASTIC_HOST}'
  indices:
    - index: "%{[datastream]}"
      when.not.equals:
        datastream: "unknown"  
    - index: "filebeat-%{[agent.version]}-%{[tenant.name]}-%{[kubernetes.container.name]}-%{+yyyy.MM.dd}"
      when.equals:
        serviceLevelIndex: "yes"
    - index: "filebeat-%{[agent.version]}-%{[tenant.name]}-%{+yyyy.MM.dd}"
      when.equals:
        tenantLevelIndex: "yes"
  bulk_max_size: '${BULK_MAX_SIZE:50}'
  worker: '${WORKER_COUNT:1}'
