filebeat.autodiscover:
  providers:
    - type: kubernetes
      templates:
        - condition:
            not:
              equals:
                kubernetes.namespace: kube-system
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.kubernetes.container.id}/*.log
              exclude_lines: ["^\\s+[\\-`('.|_]"]  # drop asciiart lines
processors:
- add_cloud_metadata: ~
- add_fields:
    target: tenant
    fields:
      name: '${TENANT_NAME:unknown}'
      id: '${TENANT_ID:unknown}'
      roleName: ${ROLE_NAME:unknown}
output.elasticsearch:
  hosts: '${ELASTIC_HOST}'