filebeat.autodiscover:
  providers:
    - type: kubernetes
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/log/containers/*-${data.container.id}.log  # CRI path
setup.template.name: "filebeat-%{[agent.version]}"
setup.template.pattern: "filebeat-%{[agent.version]}-*"    
output.elasticsearch:
  hosts: '${ELASTIC_HOST}'
  bulk_max_size: '${BULK_MAX_SIZE:50}'
  worker: '${WORKER_COUNT:1}'
