filebeat.autodiscover:
  providers:
    - type: kubernetes
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/lib/docker/containers/1eb0f01affb9b77102610bc4f36d80f26193e3ac38c60b8686c12fdc1834c672/1eb0f01affb9b77102610bc4f36d80f26193e3ac38c60b8686c12fdc1834c672-json.log.4
processors:
- add_cloud_metadata: ~
- add_fields:
    target: tenant
    fields:
    name: '${TENANT_NAME:unknown}'
    id: '${TENANT_ID:unknown}'
    roleName: ${ROLE_NAME:unknown}    
output.elasticsearch:
  hosts: '${ELASTIC_HOST}'
  index: "filebeat-%{[agent.version]}-2024.08.10-new"
