# Generated by generate.sh - do not edit directly.
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    duplocloud.net/daemnonset-tenant-local: "True"
  labels:
    name: fluentbit-{{NAMESPACE}}-ds
  name: fluentbit-{{NAMESPACE}}-ds
  namespace: {{NAMESPACE}}
spec:
  revisionHistoryLimit: 10
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - fluentbit-{{NAMESPACE}}-ds
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        fluentbit.io/exclude: "true"
      labels:
        app: fluentbit-{{NAMESPACE}}-ds
    spec:
      containers:
        - env:
            - name: ES_HOST
              value: "{{ES_HOST}}"
            - name: ES_PORT
              value: "443"
            - name: ES_TLS
              value: "On"
            - name: ALIAS
              value: "unknown"
            - name: TENANT_LEVEL_INDEX
              value: "yes"
            - name: SERVICE_LEVEL_INDEX
              value: "no"
            - name: INDEX_PREFIX
              value: "filebeat-fluentbit-"
          image: "{{DOCKER_IMAGE}}"
          imagePullPolicy: IfNotPresent
          name: fluentbit-{{NAMESPACE}}
          ports:
            - containerPort: 2020
              name: metrics
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              ephemeral-storage: 512Mi
              memory: 256Mi
            requests:
              cpu: 50m
              ephemeral-storage: 256Mi
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 2020
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 2020
            initialDelaySeconds: 5
            periodSeconds: 15
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
            capabilities:
              drop: [ALL]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log
              name: varlog
              readOnly: true
            - mountPath: /var/lib/fluentbit
              name: fluentbit-state
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
        tenantname: {{NAMESPACE}}
      priorityClassName: duplo-monitoring
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fluentbit-{{NAMESPACE}}-sa
      serviceAccountName: fluentbit-{{NAMESPACE}}-sa
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          key: duplocloud.net/spot-instance
          operator: Exists
      volumes:
        - hostPath:
            path: /var/log
            type: ""
          name: varlog
        - hostPath:
            path: /var/lib/fluentbit-data
            type: ""
          name: fluentbit-state
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
