filebeat.autodiscover:
  providers:
    - type: kubernetes
      hints.enabled: true
processors:
- add_cloud_metadata: ~
- add_fields:
    target: tenant
    fields:
      name: '${TENANT_NAME:unknown}'
      id: '${TENANT_ID:unknown}'
      roleName: ${ROLE_NAME:unknown}

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:localhost:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
setup.kibana:
  host: "localhost:9200"