version: '3.2'
services:
  elasticsearch:
    build: ./es
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
      # (!) TLS certificates. Generate using instructions from tls/README.md.
    image: "duplocloud/elasticsearch:8.5.3-r1"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk
  kibana:
    build: ./kibana/
    image: "duplocloud/kibana:8.5.3-r1"
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
