name: Custom filebeat image build

on:
  push:
    branches: [ "filebeat-custom" ]
  pull_request:
    branches: [ "filebeat-custom" ]

defaults:
  run:
    working-directory: diagnostics/opensearch/filebeat
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and push native docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     platforms: linux/arm64,linux/amd64
      #     file: diagnostics/opensearch/filebeat/Dockerfile
      #     tags: duplocloud/filebeat-oss:7.11.1-${{ github.sha }}
      # - name: Build and push k8s docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     platforms: linux/arm64,linux/amd64
      #     file: diagnostics/opensearch/filebeat/Dockerfile-k8s
      #     tags: duplocloud/filebeat-oss:7.11.1-${{ github.sha }}-k8s  
      - name: Build and push custom docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64
          file: diagnostics/opensearch/filebeat/Dockerfile-custom
          tags: duplocloud/filebeat-oss:7.11.1-${{ github.sha }}-windows-custom   
