name: Logstash image build

on:
  push:
    branches: 
      - azure-event-hub
      - ayush-logstash-changes
  pull_request:
    branches: 
      - azure-event-hub
  workflow_dispatch:

defaults:
  run:
    working-directory: diagnostics/opensearch/logstash
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push native docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: diagnostics/opensearch/logstash/Dockerfile
          tags: duplocloud/logstash:${{ github.sha }}    
